apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-dialog-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/phoenix1881/Medical-Chatbot-MLOps
    targetRevision: main   
    path: k8s              
  destination:
    server: https://kubernetes.default.svc
    namespace: default      
  syncPolicy:
    automated:             
      prune: true        
      selfHeal: true      
