version: '3'
volumes:
  medicaldata:

services:
  extract-data:
    container_name: etl_extract_medquad
    image: python:3.11
    user: root
    volumes:
      - medicaldata:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        pip install datasets

        echo "Downloading MedQuAD dataset and saving in Arrow format..."
        python3 -c '
        from datasets import load_dataset
        ds = load_dataset("lavita/MedQuAD")
        ds.save_to_disk("/data/medquad-raw")
        '

        echo "Extract stage complete. Contents:"
        ls -lh /data

  transform-data:
    container_name: etl_transform_medquad_split
    image: python:3.11
    user: root
    volumes:
      - medicaldata:/data
      - ./split_medquad_filtered.py:/split_script.py
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        pip install datasets pandas

        echo "Filtering and splitting MedQuAD from Arrow format..."
        python3 /split_script.py

        echo "Split stage complete. Contents:"
        ls -lh /data/medquad-split

  load-data:
    container_name: etl_load_medquad_json
    image: rclone/rclone:latest
    volumes:
      - medicaldata:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
            echo "ERROR: RCLONE_CONTAINER is not set"
            exit 1
        fi

        echo "Uploading MedQuAD splits to object store..."
        rclone copy /data/medquad-split chi_tacc:$RCLONE_CONTAINER --progress

        echo "Upload complete. Listing uploaded files:"
        rclone ls chi_uc:$RCLONE_CONTAINER
