apiVersion: v1
kind: Service
metadata:
  name: dr-dialog-service
spec:
  selector:
    app: dr-dialog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort
