all:
  hosts:
    node1:
      ansible_host: 192.168.17.25
      ansible_user: cc
      ip: 192.168.17.25
      access_ip: 192.168.17.25
    node2:
      ansible_host: 192.168.17.26
      ansible_user: cc
      ip: 192.168.17.26
      access_ip: 192.168.17.26
    node3:
      ansible_host: 192.168.17.27
      ansible_user: cc
      ip: 192.168.17.27
      access_ip: 192.168.17.27
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
