apiVersion: apps/v1
kind: Deployment
metadata:
  name: medchat-deployment
  labels:
    app: medchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medchat
  template:
    metadata:
      labels:
        app: medchat
    spec:
      containers:
      - name: medchat
        image: phoenix1881/medchat:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: medchat-service
spec:
  type: ClusterIP
  selector:
    app: medchat
  ports:
    - port: 80
      targetPort: 5000
