version: "3.8"
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.10-py3
    restart: always
    shm_size: 1g
    ports:
      - "8000:8000"   # HTTP
      - "8001:8001"   # gRPC
      - "8002:8002"   # Metrics
    volumes:
      - ./triton_model_repo:/models
    command: tritonserver --model-repository=/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Remove if using CPU
